controller:
  # STATE CONTROLLER / STATE PUBLISHER
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 300

  # POSITION CONTROLLER
  position_controller:
    type: position_controllers/JointPositionController
    joint: dynamixel_test_joint

  # VELOCITY CONTROLLER
  velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: dynamixel_test_joint

  # EFFORT CONTROLLER
  effort_controller:
    type: effort_controllers/JointPositionController
    joint: dynamixel_test_joint
