motor_poles: 20
overvoltage_protection: 1
driver_switch: 1
ramp_switch: 0
communication_mode: 6
target_reached_distance: 5
target_reached_velocity: 5
motor_halted_velocity: 5
maximum_current: 1000
position_p_parameter: 300
velocity_p_parameter: 500
velocity_i_parameter: 500
current_p_parameter: 300
current_i_parameter: 300
