config:
  # Torque (0: off, 1: on)
  - identifier: torque_switch
    value: 0
  # Drive Mode (0: normal operation, 1: inverted operation)
  - identifier: drive_mode
    value: 1
  # Operating Modes:
  # 0: Current Control Mode
  # 1: Velocity Control Mode
  # 3: Position Control Mode
  # 4: Extended Position Control Mode(Multi-turn)
  # 5: Current-based Position Control Mode
  - identifier: operating_mode
    value: 5
  - identifier: current_limit
    value: 200
  # Homing offset (0-4095)
  - identifier: homing_offset
    value: 2048
  # Minimum Position Limit (0-4095)
  - identifier: min_position_limit
    value: 1764      #   2048 - identifier: round (25 * (4096 / 360))
  # Maximum Position Limit (0-4095)
  - identifier: max_position_limit
    value: 2332      # 2048 + round (25 * (4096 / 360))
  # Position Controller Parameters
  - identifier: position_p_gain
    value: 100
  - identifier: position_i_gain
    value: 100
  - identifier: position_d_gain
    value: 100
  # Velocity Controller Parameters
  - identifier: velocity_p_gain
    value: 0
  - identifier: velocity_i_gain
    value: 0
  # Feedforward Parameters
  - identifier: feedforward_1st_gain
    value: 100
  - identifier: feedforward_2nd_gain
    value: 100
  # LED (0: off, 1: on)
  - identifier: led_switch
    value: 1
  - identifier: torque_switch
    value: 1
